name: Rodar monitor_logs.py

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # roda a cada hora

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip

      - name: Executar script
        run: |
          python monitor_logs.py

      - name: Fazer upload do logs.csv
        uses: actions/upload-artifact@d4051db76e20f812e0ee6c7a473c5e2c7026ca3f
        with:
          name: logs-csv
          path: logs.csv
